# --------------------------- housekeeping -------------------------------------
PEP: config/pep.yaml

# --------------------------- job options --------------------------------------
FASTERQDUMP_MEM: 24000

# mosdepth for te copy estimation
MOSDEPTH_WINDOW_SIZE: 100
MOSDEPTH_SAM_FLAG_EXCLUDE: 1540 # allows multimappers